### ISSUE TITLE
Add a custom derive macro for Cluster types

### ISSUE THREAD

**Issue by connorworley** [first-rust-competition/ni-fpga-rs#1]
Users should be able to specify Clusters as Rust structs, and use a custom derive macro to automatically implement `ni_fpga::Datatype`.

Some challenges:
* There's no API for reading or writing Clusters. They appear to always be padded to at least a multiple of 32 bits, so we can use ReadArrayU32 and WriteArrayU32.
* Unfortunately this means we'll have to marshal the u32 arrays ourselves. Most FPGA types have the same size as their equivalent Rust type, but others do not (bool is notably 1 bit on the FPGA). Now that we aren't using type-specific read/write calls, we'll have to generate code to do the marshaling. This will involve introspecting the struct and keeping track of the FPGA size and bit offset of each field.
* We can't implement `ni_fpga::Datatype` for arrays of custom structs because arrays are always foreign. This is pretty easy to get around, just generate a `struct FooArray<const N: usize>([Foo; N])` newtype and implement for that instead.

**Comment by connorworley** [comment]
I'm thinking I can lean heavily on https://github.com/hashmismatch/packed_struct.rs

**Comment by connorworley** [comment]
I can't figure out how to call a proc macro from within a proc macro, so it's looking like I'll have to generate the packing/unpacking code myself.

**Comment by auscompgeek** [comment]
@connorworley is https://stackoverflow.com/questions/49140854/how-can-i-call-one-procedural-macro-from-another useful?

**Comment by connorworley** [comment]
That worked! I'm trudging along in the cluster_derive branch now. I've decided on something like 
```rust
cluster! {
    LEDs {
        comm: u8,
        mode: u8,
        rsl: bool,
    }
}
```
for the cluster declaration syntax.

**Comment by auscompgeek** [comment]
Keep in mind the [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/).

**Comment by connorworley** [comment]
Done in #8
